sudo: required
services: 
  - docker

before_install:
  - docker build -t sregor/docker-react -f Dockerfile.dev . 

script:
  - travis_wait 30 docker run sregor/docker-react npm run test -- --coverage
