sudo: required
services: 
  - docker

before_install:
  - docker build -t sregor/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true sregor/docker-react npm run test --code--coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-dev"
  env: "Dockerdev-env"
  edge: true
  bucket_name: "elasticbeanstalk-us-east-1-153986819543"
  bucket_path: "docker-dev"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY" 