version: "3.9"
services: 
  app:
    image: "sregor/reactapp"
    build: . 
    restart: always
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    image: "sregor/reactapp"
    build: . 
    restart: always
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]
  
    